name: i_am_rich
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  audioplayers: ^6.0.0
  animated_text_kit: ^4.2.2
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.2
  modal_progress_hud_nsn: ^0.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/diamond.jpg
    - images/lab2/profile.jpg
    - images/lab3/
    - images/lab4/
    - assets/lab5/

fonts:
  - family: Pacifico
    fonts:
      - asset: fonts/Pacifico-Regular.ttf
  - family: SourceSans3
    fonts:
      - asset: fonts/SourceSans3-Regular.ttf


